CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;
USE test;
CREATE TABLE roles (id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
					createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
                    label VARCHAR(100));
